version: "3"
services:
  valheim:
    image: ghcr.io/ekman/valheim:1
    build:
      context: .
    restart: unless-stopped
    volumes:
      - "./config:/home/steam/config"
      - "./game:/home/steam/game"
    expose: [ 2456-2458:2456-2458/udp ]
    read_only: true
    environment:
      - NAME=My server
      - WORLD=My world
      - PASSWORD=secret
