version: "3"
services:
  valheim:
    image: ghcr.io/ekman/valheim:1
    restart: unless-stopped
    volumes:
      - "./config:/home/steam/config"
      - "./game:/home/steam/game"
    expose: [ 2456-2458:2456-2458/udp ]
    stop_grace_period: 2m
    tty: true
    environment:
      - NAME=My server
      - WORLD=Dedicated
      - PASSWORD=secret
